
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock


development:
  <<: *default
  database: site_locadora_carros



production:
  primary: &primary_production
    <<: *default
    database: site_locadora_carros_production
    username: site_locadora_carros
    password: <%= ENV["SITE_LOCADORA_CARROS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: site_locadora_carros_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: site_locadora_carros_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: site_locadora_carros_production_cable
    migrations_paths: db/cable_migrate
